status.py: Fix a utf-8 codec  decode error
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 307: invalid continuation byte.
First time I got that after a lot of runs.
set decode to replace errors instead of the default 'strict' setting.